def calibrate(s):
    first, last = ["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"])).index(min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))))] if min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))) > min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))) else ["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"])).index(min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))))], ["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.rfind(x), ["1", "2", "3", "4", "5", "6", "7", "8", "9"])).index(max(list(map(lambda x: s.rfind(x), ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))))] if max(list(map(lambda x: s.rfind(x), ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))) > max(list(map(lambda x: s.rfind(x), ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))) else ["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.rfind(x), ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"])).index(max(list(map(lambda x: s.rfind(x), ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))))]
    return int(["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"])).index(min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))))] if min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))) > min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))) else ["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"])).index(min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))))] + ["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"])).index(min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))))] if min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))) > min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]))) else ["1", "2", "3", "4", "5", "6", "7", "8", "9"][list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"])).index(min(list(map(lambda x: s.find(x) if s.find(x) != -1 else len(s) + 1, ["1", "2", "3", "4", "5", "6", "7", "8", "9"]))))]) if last == -1 else int(first + last)

fr = open("input.txt", "r")
lines = fr.readlines()
for i in range(len(lines)):
    lines[i] = calibrate(lines[i])
    
with open("output.txt", "w") as o:
    for i in range(len(lines)):
        o.write(str(lines[i]) + "\n")  
        
print(sum(lines))